import Assets from "@/assets/images/categories/3DAssets.png";
import Printing from "@/assets/images/categories/3DPrinting.png";
import Addons from "@/assets/images/categories/Addons.png";
import Animation from "@/assets/images/categories/Animation.png";
import Art from "@/assets/images/categories/Art.png";
import Materials from "@/assets/images/categories/Materials.png";
import Robots from "@/assets/images/categories/Robots.png";

export const categories = [
  {
    name: "Courses",
    subcategories: [
      {
        name: "Character Creation",
        subjects: [
          "Character Anatomy",
          "Character Modeling",
          "Character Sculpting",
          "Stylized Characters",
        ],
        image: Art,
      },
      {
        name: "Hard Surface Modeling",
        subjects: ["Vehicles", "Weapons", "Robots"],
        image: Assets,
      },
      {
        name: "Sculpting",
        subjects: [
          "Human Body",
          "Human Head",
          "Animals",
          "Creatures",
          "Environments",
          "Props",
          "Plants & Trees",
        ],
        image: Printing,
      },
      {
        name: "Rigging",
        subjects: [
          "Vehicle RIgging",
          "Humanoid Rigging",
          "Weapon Rigging",
          "Animal R",
        ],
        image: Robots,
      },
      {
        name: "Animation",
        subjects: [
          "Character Animation",
          "Vehicles Animation",
          "Weapon Animation",
          "Animal Animation",
        ],
        image: Animation,
      },
      {
        name: "Environment Design",
        subjects: ["Sci-fi environment", "Natural Environment"],
        image: Addons,
      },
      {
        name: "Cloth",
        subjects: ["Cloth Design", "Cloth Simulation"],
        image: Art,
      },
      {
        name: "VFX",
        subjects: [
          "Compositing",
          "Camera Tracking",
          "Matt Painting",
          "Simulation",
        ],
        image: Materials,
      },
      {
        name: "Archviz",
        subjects: ["Interior Visualization", "Exterior Visualization"],
        image: Assets,
      },
      {
        name: "Lighting",
        image: Printing,
      },
      {
        name: "CAD Modeling",
        image: Robots,
      },
      {
        name: "3D Printing",
        image: Animation,
      },
      {
        name: "Texturing",
        image: Addons,
      },
    ],
  },
  {
    name: "Addons",
    subcategories: [
      {
        name: "Modeling",
        subjects: [
          "Hard Surface Modeling",
          "Sculpting",
          "Retopology",
          "Archviz Modeling",
          "CAD Modeling",
        ],
        image: Addons,
      },
      {
        name: "Simulation",
        subjects: [
          "Cloth",
          "Damage Destruction",
          "Fire & Explosions",
          "Fluids & Water",
          "Hair & Fur",
          "Physics & Dynamics",
          "Crowd Simulation",
          "Energy FX",
          "VDB Addons",
        ],
        image: Materials,
      },
      {
        name: "Enviromnet Creation",
        subjects: [
          "Atmosphere & Skies",
          "Terrain Generation",
          "Buildings",
          "Roads & Streets",
          "Clouds",
          "Fog",
          "Space",
          "Water/See/Ocean",
          "Scattering",
          "Vegetation",
          "Weather FX",
        ],
        image: Assets,
      },
      {
        name: "Texturing",
        subjects: ["Texture Painting", "Material Libraries", "Texture Baking"],
        image: Printing,
      },
      {
        name: "Rigging",
        subjects: ["Facial Rigging", "Skinning & Weight painting"],
        image: Robots,
      },
      {
        name: "2D Addons",
        subjects: ["Grease Pencil", "Cell Shading", "Pixal Art"],
        image: Printing,
      },
      {
        name: "Sci-Fi",
        subjects: ["Spaceships", "Generative Sci-fi"],
        image: Assets,
      },
      { name: "Nodes", subjects: ["Geometry Nodes"], image: Materials },
      { name: "Animation", image: Animation },
      { name: "Compositing", image: Printing },
      { name: "AI", image: Assets },
      { name: "Character Creation", image: Animation },
      { name: "Clouds", image: Addons },
      { name: "Asset Managment", image: Materials },
      { name: "Rendering", image: Printing },
      { name: "Motion Graphics", image: Animation },
      { name: "Sound", image: Art },
    ],
  },
  {
    name: "Materials",
    subcategories: [
      { name: "Wood", image: Materials },
      { name: "Metal", image: Robots },
      { name: "Plastic", image: Assets },
      { name: "Glass", image: Art },
      { name: "Concrete", image: Printing },
      { name: "Fabric", image: Addons },
      { name: "Rubber", image: Animation },
      { name: "Asphalt", image: Assets },
      { name: "Marble", image: Materials },
      { name: "Tile", image: Printing },
      { name: "Grass", image: Robots },
      { name: "Water", image: Art },
      { name: "Snow", image: Addons },
      { name: "Sand", image: Animation },
      { name: "Dirt", image: Assets },
    ],
  },
  {
    name: "Shaders",
    subcategories: [
      { name: "Glass", image: Art },
      { name: "Metal", image: Printing },
      { name: "Plastic", image: Robots },
      { name: "Fabric", image: Assets },
      { name: "Leather", image: Materials },
      { name: "Stone", image: Animation },
      { name: "Brick", image: Addons },
      { name: "Ceramic", image: Art },
      { name: "Paper", image: Printing },
      { name: "Paint", image: Robots },
      { name: "Carpet", image: Materials },
      { name: "Rubber", image: Animation },
      { name: "Asphalt", image: Addons },
      { name: "Marble", image: Art },
      { name: "Tile", image: Printing },
      { name: "Grass", image: Robots },
    ],
  },
  {
    name: "Brushes",
    subcategories: [
      { name: "Character", image: Materials },
      { name: "Environment", image: Animation },
      { name: "Props", image: Assets },
      { name: "Plants & Trees", image: Printing },
      { name: "Vehicles", image: Art },
      { name: "Weapons", image: Addons },
      { name: "Cloth", image: Animation },
      { name: "Hair", image: Materials },
      { name: "Fur", image: Printing },
      { name: "Skin", image: Assets },
      { name: "Materials", image: Art },
      { name: "Shaders", image: Animation },
      { name: "Textures", image: Addons },
      { name: "HDRI", image: Materials },
      { name: "Lighting", image: Printing },
      { name: "VFX", image: Art },
      { name: "Archviz", image: Assets },
      { name: "CAD Modeling", image: Animation },
      { name: "3D Printing", image: Addons },
      { name: "Texturing", image: Materials },
    ],
  },
  {
    name: "Models",
    subcategories: [
      { name: "Hair", image: Printing },
      { name: "Fur", image: Robots },
      { name: "Skin", image: Assets },
      { name: "Materials", image: Art },
      { name: "Shaders", image: Addons },
      { name: "Textures", image: Animation },
      { name: "HDRI", image: Materials },
      { name: "Lighting", image: Printing },
      { name: "VFX", image: Art },
      { name: "Archviz", image: Assets },
      { name: "CAD Modeling", image: Addons },
      { name: "3D Printing", image: Animation },
      { name: "Texturing", image: Materials },
    ],
  },
];
