import Assets from "@/assets/images/categories/3DAssets.png";
import Printing from "@/assets/images/categories/3DPrinting.png";
import Addons from "@/assets/images/categories/Addons.png";
import Animation from "@/assets/images/categories/Animation.png";
import Art from "@/assets/images/categories/Art.png";
import Materials from "@/assets/images/categories/Materials.png";
import Robots from "@/assets/images/categories/Robots.png";

export const products = [
  {
    id: 1,
    title: "3D Assets for FPS Games",
    image: Assets,
    rating: 4,
    price: 100,
    description:
      "ransportation is a complete Blender add-on that does not only help manage a huge library of HD vehicles and cars rigged on Blender. but also, shaders, hdri and backplates. With Transportation you can create incredible images in few seconds!   It is ideal for architects, designers, and CG artists.",
    productshopsinfo: [
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 1,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 2,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 3,
      },
    ],
  },
  {
    id: 2,
    title: "Ready to Print 3D Models",
    image: Printing,
    rating: 4,
    price: 100,
    description: "Ready to Print 3D Models",
    productshopsinfo: [
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 1,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 2,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 3,
      },
    ],
  },
  {
    id: 3,
    title: "Addons for 3D Models",
    image: Addons,
    rating: 4,
    price: 100,
    description: "Addons for 3D Models",
    productshopsinfo: [
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 1,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 2,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 3,
      },
    ],
  },
  {
    id: 4,
    title: "3D Animation on Demand",
    image: Animation,
    rating: 4,
    price: 100,
    description: "3D Animation on Demand",
    productshopsinfo: [
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 1,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 2,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 3,
      },
    ],
  },
  {
    id: 5,
    title: "Art and Design Services",
    image: Art,
    rating: 4,
    price: 100,
    description: "Art and Design Services",
    productshopsinfo: [
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 1,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 2,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 3,
      },
    ],
  },
  {
    id: 6,
    title: "Materials for 3D Printing",
    image: Materials,
    rating: 4,
    price: 100,
    description: "Materials for 3D Printing",
    productshopsinfo: [
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 1,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 2,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 3,
      },
    ],
  },
  {
    id: 7,
    title: "Robots and Drones",
    image: Robots,
    rating: 4,
    price: 100,
    description: "Robots and Drones",
    productshopsinfo: [
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 1,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 2,
      },
      {
        price: 100,
        currency: "$",
        rating: 4,
        software: "Blender",
        license: "Standar",
        productlink: "https://www.google.com",
        shopid: 3,
      },
    ],
  },
];
